name: Build Latest Server Image

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  publish-docker-image:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Build Veritas Image
        uses: VaultVulp/gp-docker-action@1.2.0
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          image-name: veritas-server
          build-context: ./server
