name: Build Latest Server Image

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  publish-docker-image:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2

      - name: Authenticate with GitHub
        run: docker login -u publisher -p ${{ secrets.GITHUB_TOKEN }} ghcr.io

      - name: Build Docker Image
        run: docker build -t ghcr.io/graytonio/openveritas/veritas-server:latest -f Dockerfile-server ./

      - name: Push Docker Image
        run: push ghcr.io/graytonio/openveritas/veritas-server:latest
