name: Build Release Server Image

on:
  release:
    types: ["published"]

jobs:
  publish-docker-image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Authenticate with GitHub
        run: docker login -u publisher -p ${{ secrets.GITHUB_TOKEN }} ghcr.io

      - name: Build Docker Image
        run: docker build -t ghcr.io/graytonio/openveritas/veritas-server:$(echo ${GITHUB_REF} | sed -e "s/refs\/tags\///g") -f Dockerfile-server ./

      - name: Push Docker Image
        run: docker push ghcr.io/graytonio/openveritas/veritas-server:$(echo ${GITHUB_REF} | sed -e "s/refs\/tags\///g")
