name: Run test suite against build binary

# TODO

on:
  push: 
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-binary:
    runs-on: ubuntu-20.04
    permissions:
      contents: read
      packages: write
    steps:
      - uses: phwes/simple_hello_world@v1